### ISSUE TITLE
Propuesta " Incorporar sección de tecnologías"

### ISSUE THREAD

**Issue by margarita264** [AlexZerpa/portfolio-template#1]
# Propuesta " Incorporar sección de tecnologías"
Hola Alex, veo que a tu portfolio le falta una sección de tecnologías en las cuales trabajas. Es recomendable agregar las tecnologías que manejas profesionalmente para que los reclutadores vean tus conocimientos...😊
Saludos ✌

**Comment by AlexZerpa** [comment]
Gracias Margarita por las recomendaciones en la nueva seccion de mi portafolio. Issue closed
